### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by remojansen** [Ryzee119/hawk#3]
Hi, I saw this and wondered if the following would be possible:

## Bluetooth-capable version

Create a new version that includes a Bluetooth transceiver so wireless headphones are compatible. I guess that you will also require a small LCD to list the Bluetooth devices that have been detected. I don't see why this could not work with factory models.

## Game audio capable (moded-xbox only)

The OG Xbox communicator only plays party chat audio. However, could the BIOS or OS be configured to route game audio to the controller? It would be great to listen to both party and game audio via headphones. I'm not sure if it is possible at a hardware level, but for example, the game Manhunt played some in-game sound effects through the communicator. So, I guess that it should be possible (it might require lowering the audio quality).

Thanks for your excellent work!

**Comment by Ryzee119** [comment]
Closing as not really an issue and out of the scope of this project.

I'm sure it is all possible. Maybe you or someone else could give it a shot
